---
include:
  - board: mikoto@7.2//zmk
    shield: lily58_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
  - board: mikoto@7.2//zmk
    shield: lily58_right nice_view_adapter nice_view
